### ISSUE TITLE
Room Endpoints

### ISSUE THREAD

**Issue by SHIV5T3R** [SHIV5T3R/CO-DE#12]
This issue focuses on implementing the room management functionality for the backend, enabling users to create, join, and collaborate in shared project rooms. By integrating this feature, the application will provide a comprehensive environment for real-time collaboration and effective communication within project rooms.

# Expected Behavior

## API Endpoints

Implement a set of API endpoints to handle room-related actions, including room creation, joining, leaving, and retrieving room details.

## WebSockets Integration

Integrate WebSockets to enable real-time communication and collaboration within project rooms. WebSocket connections should be established upon joining a room and should handle events like code sharing and chat messages.

## Room Creation

API endpoint for creating new project rooms, allowing users to provide necessary information such as room name, description, and privacy settings.

## Room Joining

API endpoint for joining existing project rooms, validating user access and enabling WebSocket connections for real-time collaboration.

## Room Details

API endpoint for retrieving detailed information about a specific project room, including its members, shared files, and ongoing collaboration activities.

## Collaboration Events

WebSockets should handle real-time collaboration events, such as code sharing, file uploads, and chat messages, ensuring seamless communication within project rooms.

## User Authentication and Authorization

Ensure that users are authenticated and authorized properly to access and participate in project rooms.

Notifications: Implement WebSocket-based notifications for room invitations, updates, and new messages within project rooms.

## Leaving a room

API endpoint for leaving a project room, revoking access and cleaning up associated resources.

---

By implementing the room management feature with both APIs and WebSockets, the application will provide a powerful platform for collaborative project work. This feature will empower users to create, join, and collaborate on shared initiatives seamlessly, enhancing the overall user experience and facilitating effective teamwork.

**Comment by blackmouse572** [comment]
Just need a discussion about model to do this task, cheer 🎉

**Comment by believemanasseh** [comment]
I would like to collaborate on this task. Thanks

**Comment by guledm12** [comment]
I would also like to collaborate on this task

**Comment by DatMomoAgain** [comment]
I would like to collaborate. Discord username: datmomoagain. 
Right now I only know @believemanasseh discord username, if anyone else wants to collaborate please mention your usernames

**Comment by guledm12** [comment]
> I would like to collaborate. Discord username: datmomoagain.
> Right now I only know @believemanasseh discord username, if anyone else wants to collaborate please mention your usernames

@DatMomoAgain My discord username is the same as my GitHub username
