### ISSUE TITLE
Mobile implementation?

### ISSUE THREAD

**Issue by danielmc02** [SHIV5T3R/CO-DE#7]
Are all priorities currently focused on web implementation (regarding front-end)? I'm capable of starting and managing a mobile version and keeping up with themes, Api, functionality, etc.

**Comment by SHIV5T3R** [comment]
Yeah, it's a website. There wouldn't be support for mobile, at least for now.

**Comment by MrBisquit** [comment]
It's a nice idea though, maybe at some point.
